name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]
  
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run tests
      - run: npm run testCodeQuality
